---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: kubernetes.core
    version: 5.2.0
  - name: community.docker
    version: 4.3.1
  - name: community.general
    version: 10.3.0
  - name: community.postgresql
    version: 3.9.1
  - name: community.windows
    version: 2.3.0
