---
desired_state: present
semaphore_download_package: true
semaphore_dependencies:
  - ansible-core
  - python3.12-devel
  - python3.12-pip
  - python3.12-pip-wheel
  - psmisc
  - rsync
  - tar
  - zip
# timer to execute requirements-update
requirements_timer: '*-*-* 20:30:40'
verify_state: true
# Easier debugging
debug: false
semaphore_config_path: config.json.j2
semaphore_port: 3000
semaphore_db_host: "{{ postgres_listen_addresses }}"
bind_port: 3000
semaphore_service_uri: "https://{{ ansible_fqdn | default(ansible_hostname) }}"
# Whether to create an admin user
semaphore_admin_user_manage: true
# Use ansible-vault to encrypt values vars/main.yml refers to the vault_* variables
vault_admin_user: admin
vault_admin_email: nobody@localhost.localdomain
