#!/usr/bin/env ansible-playbook
# export DB_PASS=aVeryStrongDatabasePassword
---

- name: Database Server
  hosts: database
  become: true
  gather_facts: true
  tags: [postgres, database]

  pre_tasks:
    - name: Lookup DB_PASS in environment variables
      when: desired_state == 'present'
      ansible.builtin.set_fact:
        check_db_pass: "{{ lookup('env', 'DB_PASS') }}"
      no_log: true

    - name: Assert that DB_PASS is defined
      when: desired_state == 'present'
      ansible.builtin.assert:
        that:
          - check_db_pass | length > 8
        msg: |
          run this shell command before this playbook:
          read -sp "Enter database password: " DB_PASS && export DB_PASS ; echo

  roles:
    - role: bbaassssiiee.postgres_ssl


- name: Tools
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [tools]

  tasks:
    - name: Install Helm
      when:
        - use_helm is defined
        - use_helm | bool
      ansible.builtin.include_role:
        name: andrewrothstein.kubernetes_helm

    - name: Install Krew
      when:
        - use_krew is defined
        - use_krew | bool
      ansible.builtin.include_role:
        name: andrewrothstein.krew

    - name: Install kbcli
      when:
        - use_kbcli is defined
        - use_kbcli | bool
      ansible.builtin.include_role:
        name: bbaassssiiee.kubeblocks

    - name: Install k9
      when:
        - use_k9s is defined
        - use_k9s | bool
      ansible.builtin.include_role:
        name: andrewrothstein.k9s

    - name: Install OpenTofu
      when:
        - use_opentofu is defined
        - use_opentofu | bool
      ansible.builtin.include_role:
        name: andrewrothstein.opentofu

    - name: Install Powershell
      when:
        - use_powershell is defined
        - use_powershell | bool
      ansible.builtin.include_role:
        name: andrewrothstein.powershell

    - name: Install Terraform
      when:
        - use_terraform is defined
        - use_terraform | bool
      ansible.builtin.include_role:
        name: andrewrothstein.terraform

- name: Reverse Proxy
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: Install nginx
      ansible.builtin.include_role:
        name: bbaassssiiee.nginx_ssl
      tags: [nginx]

- name: Forward Proxy
  hosts: proxy
  become: true
  gather_facts: true
  tags: [proxy]
  vars:
    docker_users:
      - semaphore
  tasks:
    - name: Install Docker
      when: use_docker | bool
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Install Squid proxy
      ansible.builtin.include_role:
        name: bbaassssiiee.proxy
      tags: [proxy]

- name: Semaphore in Systemd
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [semaphore]

  pre_tasks:
    - name: Lookup SSH_PASS in environment variables
      ansible.builtin.set_fact:
        ssh_passphrase: "{{ lookup('env', 'SSH_PASS') }}"
      no_log: true

    - name: Assert that SSH_PASS is defined
      ansible.builtin.assert:
        that:
          - ssh_passphrase | length > 8
        msg: |
          run this shell command before this playbook:
          read -sp "Enter ssh key passphrase: " SSH_PASS && export SSH_PASS ; echo
  tasks:
    - name: Install Docker
      when: use_docker | bool
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Install Semaphore
      ansible.builtin.include_role:
        name: semaphore

- name: Configure Semaphore
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [api]

  vars:
    semaphore_api_url: "http://localhost:3000/api"
    semaphore_username: semaphore

  module_defaults:
    ansible.builtin.uri:
      use_proxy: false
      headers:
        Content-Type: "application/json"
      body_format: json
      validate_certs: false
      timeout: 5

  tasks:
    - name: Configure Semaphore
      ansible.builtin.include_role:
        name: api
      tags:
        - api
