#!/usr/bin/env ansible-playbook
# export DB_PASS=aVeryStrongDatabasePassword
---

- name: Database Server
  hosts: database
  become: true
  gather_facts: true
  tags: [postgres, database]

  pre_tasks:
    - name: Lookup DB_PASS in environment variables
      when: desired_state == 'present'
      ansible.builtin.set_fact:
        check_db_pass: "{{ lookup('env', 'DB_PASS') }}"
      no_log: true

    - name: Assert that DB_PASS is defined
      when: desired_state == 'present'
      ansible.builtin.assert:
        that:
          - check_db_pass | length > 8
        msg: |
          run this shell command before this playbook:
          read -sp "Enter database password: " DB_PASS && export DB_PASS ; echo

  roles:
    - role: postgres

- name: Semaphore in Systemd
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [semaphore]

  pre_tasks:
    - name: Lookup SSH_PASS in environment variables
      ansible.builtin.set_fact:
        ssh_passphrase: "{{ lookup('env', 'SSH_PASS') }}"
      no_log: true

    - name: Assert that SSH_PASS is defined
      ansible.builtin.assert:
        that:
          - ssh_passphrase | length > 8
        msg: |
          run this shell command before this playbook:
          read -sp "Enter ssh key passphrase: " SSH_PASS && export SSH_PASS ; echo

- name: Forward Proxy
  hosts: proxy
  become: true
  gather_facts: true
  tags: [proxy]
  tasks:
    - name: Install Docker
      when: use_docker | bool
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Install Squid proxy
      ansible.builtin.import_role:
        name: proxy
      tags: [proxy]

- name: Tools
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [tools]

  vars:
    docker_users:
      - semaphore

  tasks:
    - name: Install OpenTofu
      when: use_opentofu | bool
      ansible.builtin.include_role:
        name: andrewrothstein.opentofu

    - name: Install Powershell
      when: use_powershell | bool
      ansible.builtin.include_role:
        name: andrewrothstein.powershell

    - name: Install Terraform
      when: use_terraform | bool
      ansible.builtin.include_role:
        name: andrewrothstein.terraform

- name: Configure Semaphore
  hosts: semaphore
  become: true
  gather_facts: true

  vars:
    semaphore_api_url: "http://localhost:3000/api"
    semaphore_username: semaphore

  module_defaults:
    ansible.builtin.uri:
      use_proxy: false
      headers:
        Content-Type: "application/json"
      body_format: json
      validate_certs: false
      timeout: 5

  tasks:
  roles:
    - role: api
      tags:
        - api

- name: Reverse Proxy
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: nginx
      tags: [nginx]
