#!/usr/bin/env ansible-playbook
# export DB_PASS=aVeryStrongDatabasePassword
---

- name: Database Server
  hosts: database
  become: true
  gather_facts: true
  tags: [postgres, database]

  pre_tasks:
    - name: Lookup DB_PASS in environment variables
      ansible.builtin.set_fact:
        check_db_pass: "{{ lookup('env', 'DB_PASS') }}"
      no_log: true

    - name: Assert that DB_PASS is defined
      ansible.builtin.assert:
        that:
          - check_db_pass | length > 8
        msg: |
          run this shell command before this playbook:
          export DB_PASS=aVeryStrongDatabasePassword

  roles:
    - role: postgres

- name: Tools
  hosts: semaphore
  become: true
  gather_facts: true
  tags: [tools]
  tasks:
    - name: Install Docker
      when: use_docker | bool
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Install OpenTofu
      when: use_opentofu | bool
      ansible.builtin.include_role:
        name: andrewrothstein.opentofu

    - name: Install Powershell
      when: use_powershell | bool
      ansible.builtin.include_role:
        name: andrewrothstein.powershell

    - name: Install Terraform
      when: use_terraform | bool
      ansible.builtin.include_role:
        name: andrewrothstein.terraform

- name: Semaphore in Systemd
  hosts: semaphore
  become: true
  gather_facts: true
  roles:
    - role: semaphore
      tags: [semaphore]

- name: Reverse Proxy
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: nginx
      tags: [nginx]

- name: Configure Semaphore
  hosts: semaphore
  become: true
  gather_facts: true

  vars:
    semaphore_api_url: "http://localhost:3000/api"
    semaphore_username: semaphore

  module_defaults:
    ansible.builtin.uri:
      use_proxy: false
      headers:
        Content-Type: "application/json"
      body_format: json
      validate_certs: false
      timeout: 5

  tasks:
  roles:
    - role: api
      tags:
        - api
