---
- name: Set facts
  ansible.builtin.set_fact:
    semaphore_admin_user: "{{ vault_admin_user }}"
    semaphore_admin_password: "{{ vault_admin_password }}"
  no_log: "{{ not debug }}"

- name: Set API token
  ansible.builtin.uri:
    url: "{{ semaphore_api_url }}/auth/login"
    method: POST
    body:
      auth: "{{ semaphore_admin_user }}"
      password: "{{ semaphore_admin_password }}"
    status_code: 204
    timeout: 5
  register: login_response
  no_log: "{{ not debug }}"

- name: Save Cookie
  when: login_response.status == 204
  ansible.builtin.set_fact:
    cookie: "{{ login_response.cookies_string }}"
  no_log: true

-
