---
semaphore_releases_url: 'https://github.com/semaphoreui/semaphore/releases/download'
semaphore_config_dir: /etc/semaphore
semaphore_env: /home/semaphore/.env
semaphore_admin_user: "{{ vault_admin_user }}"
semaphore_admin_email: "{{ vault_admin_email }}"
semaphore_admin_password: "{{ vault_admin_password }}"
semaphore_cookie_hash: "{{ vault_cookie_hash }}"
semaphore_cookie_encryption: "{{ vault_cookie_encryption }}"
semaphore_access_key_encryption: "{{ vault_access_key_encryption }}"
ssh_passphrase: "{{ vault_ssh_passphrase | default('') }}"
