---
- name: Restart semaphore
  ansible.builtin.systemd:
    name: semaphore
    state: restarted

- name: Requirements update
  ansible.builtin.systemd:
    name: requirements.service
    daemon_reload: true
    state: started
