---
- name: Gather service facts
  ansible.builtin.service_facts:
  no_log: "{{ not debug }}"

- name: Stop semaphore service
  when:
    - ansible_facts.services['semaphore.service'] is defined
    - ansible_facts.services['semaphore.service'].state == 'running'
  ansible.builtin.systemd:
    name: semaphore.service
    state: stopped

- name: Stop and disable semaphore service
  when:
    - ansible_facts.services['semaphore.service'] is defined
    - ansible_facts.services['semaphore.service'].status == 'enabled'
  ansible.builtin.systemd:
    name: semaphore.service
    enabled: false
    daemon_reload: true

- name: Remove systemd service file
  ansible.builtin.file:
    path: /usr/lib/systemd/system/semaphore.service
    state: absent

- name: Kill processes of semaphore user
  ansible.builtin.command:
    cmd: killall -u semaphore
  register: killed
  failed_when: killed.rc not in [0, 1]
  changed_when: killed.rc == 0

- name: Remove config directory
  ansible.builtin.file:
    path: /etc/semaphore
    state: absent

- name: Remove semaphore user
  ansible.builtin.user:
    name: semaphore
    state: absent

- name: Remove semaphore package
  ansible.builtin.package:
    name: semaphore
    state: absent
