# Verify desired state, both absent and present can be verified.
---
- name: Gather service facts
  ansible.builtin.service_facts:
  no_log: "{{ not debug }}"

- name: Test the service
  when: desired_state == 'present'
  block:
    - name: Assert that service is OK
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_facts.services['semaphore.service'].status == 'enabled'
          - ansible_facts.services['semaphore.service'].state == 'running'

    - name: Verify port is listening
      ansible.builtin.wait_for:
        port: "{{ semaphore_port }}"
        state: started
        timeout: 180

- name: Test the service absence
  when: desired_state == 'absent'
  block:
    - name: Test the service absence
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_facts.services['semaphore'] is not defined

    - name: Verify port is closed
      ansible.builtin.wait_for:
        port: "{{ semaphore_port }}"
        state: stopped
        timeout: 180
