---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: azure.azcollection
  - name: chocolatey.chocolatey
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.general
  - name: community.hashi_vault
  - name: community.libvirt
  - name: community.mongodb
  - name: community.mysql
  - name: community.network
  - name: community.postgresql
  - name: community.rabbitmq
  - name: community.windows
  - name: community.zabbix
  - name: containers.podman
  - name: fortinet.fortimanager
  - name: fortinet.fortios
  - name: google.cloud
  - name: hetzner.cloud
  - name: kubernetes.core
  - name: kubevirt.core
  - name: microsoft.ad
  - name: netapp.ontap
  - name: netapp.netbox
  - name: vmware.vmware
